/** @jsxRuntime classic */
/** @jsx jsx */
import { css, jsx } from "@emotion/react";

import type { NextPage } from "next";
import Head from "next/head";

import { FC, useState } from "react";
import Layout from "@components/Layout";
import Header from "@components/Header";
import Body from "@components/Body";
import Listpage from "@components/Listpage";
import Detailpage from "@components/Detailpage";
import Ownedpage from "@components/Ownedpage";

const color = "white";

const example = css`
  padding: 32px;
  background-color: hotpink;
  font-size: 24px;
  border-radius: 4px;
  &:hover {
    color: ${color};
  }
`;

const containerStyle = css`
  padding: 0 0.5rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
  width: 100%;
  overflow: hidden;
`;

interface ContentPropsType {
  page: string;
}

const Content: FC<ContentPropsType> = (props) => {
  const { page, ...other } = props;

  switch (page) {
    case "LISTPAGE":
      return <Listpage />;

    case "DETAILPAGE":
      return <Detailpage />;

    case "OWNEDPAGE":
      return <Ownedpage />;
  }
};

const Home: NextPage = () => {
  const [currentPage, setCurrentPage] = useState<string>("LISTPAGE");

  return (
    <div>
      <Head>
        <title>Pokemon Cool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Header />
        <Body>
          <Content page={currentPage} />
        </Body>
      </Layout>
    </div>
  );
};

export default Home;
